import{a as S,S as q,i as n}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const k="49643910-5d5e059a0d787f0a1574b38c1";async function m(r,t){const a=new URLSearchParams({key:k,q:r,page:t,per_page:15,orientation:"horizontal",safesearch:!0,image_type:"photo"});return await S(`https://pixabay.com/api/?${a}`).then(({data:i})=>i)}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),d=document.querySelector(".js-load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:o,views:s,comments:w,downloads:v})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
        <img class="item-image"
        src="${i}"
        // alt="${e}" width = "360" height = "200"
        />
        </a>
        <div class="gallery-card">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comment:</b> ${w}</p>
        <p><b>Download:</b> ${v}</p>
        </div>
                </li> `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){h.innerHTML=""}function y(){g.classList.remove("hidden")}function p(){g.classList.add("hidden")}function b(){d.classList.remove("load-more-hidden")}function u(){d.classList.add("load-more-hidden")}const L=document.querySelector(".form");let l=1,c;L.addEventListener("submit",P);d.addEventListener("click",B);async function P(r){if(r.preventDefault(),M(),c=L.elements["search-text"].value.trim(),c===""){n.error({class:"my-toast",title:"",timeout:1e4,message:"Будь ласка, введіть пошуковий запит!",theme:"dark",position:"topRight",backgroundColor:"red"});return}y();try{const{hits:t,totalHits:a}=await m(c,l);if(t.length===0){n.error({class:"my-toast",title:"",timeout:1e4,message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",position:"topRight",backgroundColor:"red"});return}f(t),a>l*15&&b()}catch(t){console.log(t),n.error({class:"my-toast",title:"",timeout:1e4,message:"An error occurred during the request!",theme:"dark",position:"topRight",backgroundColor:"red"})}finally{p()}}async function B(){l++,u(),y();try{const{hits:r,totalHits:t}=await m(c,l);b(),f(r);const a=document.querySelectorAll(".gallery-item").length;console.log(a),a>=t&&u();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:e,behavior:"smooth"})}catch(r){console.log(r),n.info({class:"my-toast",title:"",timeout:1e4,message:"We are sorry, but you have reached the end of search results.",theme:"dark",position:"topRight",backgroundColor:"#08b84b"})}finally{p()}}
//# sourceMappingURL=index.js.map
