import{a as v,S as q,i as c}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const k="49643910-5d5e059a0d787f0a1574b38c1";async function m(o,t){const a=new URLSearchParams({key:k,q:o,page:t,per_page:15,orientation:"horizontal",safesearch:!0,image_type:"photo"});return await v(`https://pixabay.com/api/?${a}`).then(({data:i})=>i)}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),u=document.querySelector(".js-load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:a,largeImageURL:i,tags:e,likes:r,views:s,comments:w,downloads:S})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
        <img class="item-image"
        src="${i}"
        // alt="${e}" width = "360" height = "200"
        />
        </a>
        <div class="gallery-card">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comment:</b> ${w}</p>
        <p><b>Download:</b> ${S}</p>
        </div>
                </li> `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){h.innerHTML=""}function y(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function b(){u.classList.remove("load-more-hidden")}function n(){u.classList.add("load-more-hidden")}const L=document.querySelector(".form");let l=1,d;L.addEventListener("submit",P);u.addEventListener("click",B);async function P(o){if(o.preventDefault(),M(),d=L.elements["search-text"].value.trim(),d===""){c.error({class:"my-toast",title:"",timeout:1e4,message:"Будь ласка, введіть пошуковий запит!",theme:"dark",position:"topRight",backgroundColor:"red"});return}l=1,y();try{const{hits:t,totalHits:a}=await m(d,l);if(t.length===0){c.error({class:"my-toast",title:"",timeout:1e4,message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",position:"topRight",backgroundColor:"red"});return}g(t),a>l*15?b():n()}catch(t){console.log(t),n(),c.error({class:"my-toast",title:"",timeout:1e4,message:"An error occurred during the request!",theme:"dark",position:"topRight",backgroundColor:"red"})}finally{p()}}async function B(){l++,n(),y();try{const{hits:o,totalHits:t}=await m(d,l);b(),g(o);const a=document.querySelectorAll(".gallery-item").length;console.log(a),a>=t&&n(),C()}catch(o){console.log(o),n(),c.info({class:"my-toast",title:"",timeout:1e4,message:"We are sorry, but you have reached the end of search results.",theme:"dark",position:"topRight",backgroundColor:"#08b84b"})}finally{p()}}function C(){const o=document.querySelector(".gallery-item"),t=o.getBoundingClientRect().height;o&&window.scrollBy({left:0,top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
